<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">

    <?php
        echo $this->headScript();
        echo $this->headStyle();
        echo $this->headTitle('Facebook api test');
        echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
    ?>
</head>
<body>
    <div class="container mt-5">
        <?= $this->content ?>
    </div>

    <link rel="stylesheet" href="/styles.css">
    <script src="/common.js"></script>

    <?= $this->inlineScript() ?>
</body>
</html>
